2024-01-24 18:40:09,493 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 19:59:16,629 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 19:59:54,811 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:01:21,877 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:06:50,473 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:07:42,539 INFO     127.0.0.1 - - [24/Jan/2024 20:07:42] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:07:42,761 INFO     127.0.0.1 - - [24/Jan/2024 20:07:42] "[37mGET /static/style.css HTTP/1.1[0m" 200 -
2024-01-24 20:07:42,770 INFO     127.0.0.1 - - [24/Jan/2024 20:07:42] "[37mGET /static/bundle.js HTTP/1.1[0m" 200 -
2024-01-24 20:07:42,784 INFO     127.0.0.1 - - [24/Jan/2024 20:07:42] "[37mGET /static/felino.js HTTP/1.1[0m" 200 -
2024-01-24 20:07:44,128 INFO     127.0.0.1 - - [24/Jan/2024 20:07:44] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-01-24 20:07:49,619 INFO     127.0.0.1 - - [24/Jan/2024 20:07:49] "[37mGET /dataset/product.product HTTP/1.1[0m" 200 -
2024-01-24 20:07:53,340 INFO     127.0.0.1 - - [24/Jan/2024 20:07:53] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:07:57,531 INFO     127.0.0.1 - - [24/Jan/2024 20:07:57] "[37mGET /image?id=26&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:07:57,859 INFO     127.0.0.1 - - [24/Jan/2024 20:07:57] "[37mGET /image?id=14&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:07:57,959 INFO     127.0.0.1 - - [24/Jan/2024 20:07:57] "[37mGET /image?id=33&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:07:58,253 INFO     127.0.0.1 - - [24/Jan/2024 20:07:58] "[37mGET /image?id=35&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:07:58,358 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:07:58,361 INFO     127.0.0.1 - - [24/Jan/2024 20:07:58] "[35m[1mGET /image?id=10&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:07:58,528 INFO     127.0.0.1 - - [24/Jan/2024 20:07:58] "[37mGET /image?id=27&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:00,661 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:00,662 INFO     127.0.0.1 - - [24/Jan/2024 20:08:00] "[35m[1mGET /image?id=11&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:00,784 INFO     127.0.0.1 - - [24/Jan/2024 20:08:00] "[37mGET /image?id=42&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:00,952 INFO     127.0.0.1 - - [24/Jan/2024 20:08:00] "[37mGET /image?id=37&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:01,276 INFO     127.0.0.1 - - [24/Jan/2024 20:08:01] "[37mGET /image?id=15&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:01,565 INFO     127.0.0.1 - - [24/Jan/2024 20:08:01] "[37mGET /image?id=18&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:01,648 INFO     127.0.0.1 - - [24/Jan/2024 20:08:01] "[37mGET /image?id=40&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:03,808 INFO     127.0.0.1 - - [24/Jan/2024 20:08:03] "[37mGET /image?id=24&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:03,949 INFO     127.0.0.1 - - [24/Jan/2024 20:08:03] "[37mGET /image?id=41&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:03,963 INFO     127.0.0.1 - - [24/Jan/2024 20:08:03] "[37mGET /image?id=23&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:04,285 INFO     127.0.0.1 - - [24/Jan/2024 20:08:04] "[37mGET /image?id=34&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:04,306 INFO     127.0.0.1 - - [24/Jan/2024 20:08:04] "[33mGET /image?id=1&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:08:04,685 INFO     127.0.0.1 - - [24/Jan/2024 20:08:04] "[37mGET /image?id=20&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:06,684 INFO     127.0.0.1 - - [24/Jan/2024 20:08:06] "[37mGET /image?id=19&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:07,035 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:07,037 INFO     127.0.0.1 - - [24/Jan/2024 20:08:07] "[35m[1mGET /image?id=22&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:07,135 INFO     127.0.0.1 - - [24/Jan/2024 20:08:07] "[37mGET /image?id=21&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:07,283 INFO     127.0.0.1 - - [24/Jan/2024 20:08:07] "[37mGET /image?id=12&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:07,308 INFO     127.0.0.1 - - [24/Jan/2024 20:08:07] "[37mGET /image?id=31&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:07,487 INFO     127.0.0.1 - - [24/Jan/2024 20:08:07] "[37mGET /image?id=39&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:09,397 INFO     127.0.0.1 - - [24/Jan/2024 20:08:09] "[37mGET /image?id=25&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:10,146 INFO     127.0.0.1 - - [24/Jan/2024 20:08:10] "[37mGET /image?id=30&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:10,306 INFO     127.0.0.1 - - [24/Jan/2024 20:08:10] "[37mGET /image?id=36&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:10,452 INFO     127.0.0.1 - - [24/Jan/2024 20:08:10] "[37mGET /image?id=13&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:10,541 INFO     127.0.0.1 - - [24/Jan/2024 20:08:10] "[37mGET /image?id=29&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:10,637 INFO     127.0.0.1 - - [24/Jan/2024 20:08:10] "[37mGET /image?id=38&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:12,417 INFO     127.0.0.1 - - [24/Jan/2024 20:08:12] "[37mGET /image?id=28&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:13,470 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:13,478 INFO     127.0.0.1 - - [24/Jan/2024 20:08:13] "[35m[1mGET /image?id=9&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:13,503 INFO     127.0.0.1 - - [24/Jan/2024 20:08:13] "[37mGET /image?id=17&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:13,878 INFO     127.0.0.1 - - [24/Jan/2024 20:08:13] "[37mGET /image?id=32&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:14,153 INFO     127.0.0.1 - - [24/Jan/2024 20:08:14] "[37mGET /image?id=16&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:14,379 INFO     127.0.0.1 - - [24/Jan/2024 20:08:14] "[33mGET /image?id=3&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:08:15,600 INFO     127.0.0.1 - - [24/Jan/2024 20:08:15] "[37mGET /image?id=8&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:15,775 INFO     127.0.0.1 - - [24/Jan/2024 20:08:15] "[37mGET /image?id=43&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:16,307 INFO     127.0.0.1 - - [24/Jan/2024 20:08:16] "[37mGET /image?id=7&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:20,067 INFO     127.0.0.1 - - [24/Jan/2024 20:08:20] "[37mGET /dataset/product.product HTTP/1.1[0m" 200 -
2024-01-24 20:08:24,631 INFO     127.0.0.1 - - [24/Jan/2024 20:08:24] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:27,858 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:27,859 INFO     127.0.0.1 - - [24/Jan/2024 20:08:27] "[35m[1mGET /image?id=11&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:28,268 INFO     127.0.0.1 - - [24/Jan/2024 20:08:28] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:08:28,333 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:28,335 INFO     127.0.0.1 - - [24/Jan/2024 20:08:28] "[35m[1mGET /image?id=22&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:28,341 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:28,343 INFO     127.0.0.1 - - [24/Jan/2024 20:08:28] "[35m[1mGET /image?id=9&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:28,387 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:28,391 INFO     127.0.0.1 - - [24/Jan/2024 20:08:28] "[35m[1mGET /image?id=10&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:08:28,481 INFO     127.0.0.1 - - [24/Jan/2024 20:08:28] "[33mGET /image?id=1&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:08:29,858 INFO     127.0.0.1 - - [24/Jan/2024 20:08:29] "[33mGET /image?id=3&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:08:29,905 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 219, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:08:29,906 INFO     127.0.0.1 - - [24/Jan/2024 20:08:29] "[35m[1mGET /image?id=11&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:10:53,806 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:10:57,506 INFO     127.0.0.1 - - [24/Jan/2024 20:10:57] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:11:00,537 INFO     127.0.0.1 - - [24/Jan/2024 20:11:00] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:03,276 INFO     127.0.0.1 - - [24/Jan/2024 20:11:03] "[37mGET /image?id=14&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:03,690 INFO     127.0.0.1 - - [24/Jan/2024 20:11:03] "[37mGET /image?id=26&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:03,942 INFO     127.0.0.1 - - [24/Jan/2024 20:11:03] "[37mGET /image?id=33&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:04,036 INFO     127.0.0.1 - - [24/Jan/2024 20:11:04] "[37mGET /image?id=35&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:04,039 INFO     127.0.0.1 - - [24/Jan/2024 20:11:04] "[37mGET /image?id=18&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:04,212 INFO     127.0.0.1 - - [24/Jan/2024 20:11:04] "[37mGET /image?id=27&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:05,938 INFO     127.0.0.1 - - [24/Jan/2024 20:11:05] "[37mGET /image?id=20&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:06,186 INFO     127.0.0.1 - - [24/Jan/2024 20:11:06] "[37mGET /image?id=31&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:06,387 INFO     127.0.0.1 - - [24/Jan/2024 20:11:06] "[37mGET /image?id=15&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:06,504 INFO     127.0.0.1 - - [24/Jan/2024 20:11:06] "[37mGET /image?id=23&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:06,542 INFO     127.0.0.1 - - [24/Jan/2024 20:11:06] "[37mGET /image?id=19&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:09,831 INFO     127.0.0.1 - - [24/Jan/2024 20:11:09] "[37mGET /image?id=41&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:10,090 INFO     127.0.0.1 - - [24/Jan/2024 20:11:10] "[37mGET /image?id=42&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:10,093 INFO     127.0.0.1 - - [24/Jan/2024 20:11:10] "[37mGET /image?id=34&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:10,318 INFO     127.0.0.1 - - [24/Jan/2024 20:11:10] "[37mGET /image?id=40&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:10,407 INFO     127.0.0.1 - - [24/Jan/2024 20:11:10] "[37mGET /image?id=39&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:10,466 INFO     127.0.0.1 - - [24/Jan/2024 20:11:10] "[37mGET /image?id=12&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:13,486 INFO     127.0.0.1 - - [24/Jan/2024 20:11:13] "[37mGET /image?id=37&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:13,536 INFO     127.0.0.1 - - [24/Jan/2024 20:11:13] "[37mGET /image?id=24&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:13,850 INFO     127.0.0.1 - - [24/Jan/2024 20:11:13] "[37mGET /image?id=21&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:13,864 INFO     127.0.0.1 - - [24/Jan/2024 20:11:13] "[37mGET /image?id=30&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:13,982 INFO     127.0.0.1 - - [24/Jan/2024 20:11:13] "[37mGET /image?id=25&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:14,156 INFO     127.0.0.1 - - [24/Jan/2024 20:11:14] "[37mGET /image?id=36&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:16,554 INFO     127.0.0.1 - - [24/Jan/2024 20:11:16] "[37mGET /image?id=13&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:16,606 INFO     127.0.0.1 - - [24/Jan/2024 20:11:16] "[37mGET /image?id=38&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:17,058 INFO     127.0.0.1 - - [24/Jan/2024 20:11:17] "[37mGET /image?id=17&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:17,283 INFO     127.0.0.1 - - [24/Jan/2024 20:11:17] "[37mGET /image?id=28&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:17,314 INFO     127.0.0.1 - - [24/Jan/2024 20:11:17] "[37mGET /image?id=29&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:17,530 INFO     127.0.0.1 - - [24/Jan/2024 20:11:17] "[37mGET /image?id=32&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:19,311 INFO     127.0.0.1 - - [24/Jan/2024 20:11:19] "[37mGET /image?id=16&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:20,120 INFO     127.0.0.1 - - [24/Jan/2024 20:11:20] "[37mGET /image?id=8&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:20,620 INFO     127.0.0.1 - - [24/Jan/2024 20:11:20] "[37mGET /image?id=7&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:20,832 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 223, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:11:20,836 INFO     127.0.0.1 - - [24/Jan/2024 20:11:20] "[35m[1mGET /image?id=10&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:11:20,850 INFO     127.0.0.1 - - [24/Jan/2024 20:11:20] "[37mGET /image?id=43&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:11:21,281 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 223, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:11:21,282 INFO     127.0.0.1 - - [24/Jan/2024 20:11:21] "[35m[1mGET /image?id=11&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:11:22,150 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 223, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:11:22,152 INFO     127.0.0.1 - - [24/Jan/2024 20:11:22] "[35m[1mGET /image?id=22&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:11:22,369 INFO     127.0.0.1 - - [24/Jan/2024 20:11:22] "[33mGET /image?id=1&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:11:22,567 INFO     127.0.0.1 - - [24/Jan/2024 20:11:22] "[33mGET /image?id=3&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:11:22,603 ERROR    Exception on /image [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 223, in images2
    gbr = partners[0]
IndexError: list index out of range
2024-01-24 20:11:22,604 INFO     127.0.0.1 - - [24/Jan/2024 20:11:22] "[35m[1mGET /image?id=9&model=res.partner HTTP/1.1[0m" 500 -
2024-01-24 20:12:47,735 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:12:53,146 INFO     127.0.0.1 - - [24/Jan/2024 20:12:53] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:12:57,206 INFO     127.0.0.1 - - [24/Jan/2024 20:12:57] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:00,087 INFO     127.0.0.1 - - [24/Jan/2024 20:13:00] "[37mGET /image?id=14&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:00,635 INFO     127.0.0.1 - - [24/Jan/2024 20:13:00] "[37mGET /image?id=26&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:00,641 INFO     127.0.0.1 - - [24/Jan/2024 20:13:00] "[37mGET /image?id=18&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:00,643 INFO     127.0.0.1 - - [24/Jan/2024 20:13:00] "[37mGET /image?id=35&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:00,728 INFO     127.0.0.1 - - [24/Jan/2024 20:13:00] "[37mGET /image?id=27&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:00,730 INFO     127.0.0.1 - - [24/Jan/2024 20:13:00] "[37mGET /image?id=33&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:03,075 INFO     127.0.0.1 - - [24/Jan/2024 20:13:03] "[37mGET /image?id=31&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:03,676 INFO     127.0.0.1 - - [24/Jan/2024 20:13:03] "[37mGET /image?id=1&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:03,874 INFO     127.0.0.1 - - [24/Jan/2024 20:13:03] "[37mGET /image?id=42&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:03,920 INFO     127.0.0.1 - - [24/Jan/2024 20:13:03] "[37mGET /image?id=12&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:04,070 INFO     127.0.0.1 - - [24/Jan/2024 20:13:04] "[37mGET /image?id=19&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:04,080 INFO     127.0.0.1 - - [24/Jan/2024 20:13:04] "[37mGET /image?id=10&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:06,170 INFO     127.0.0.1 - - [24/Jan/2024 20:13:06] "[37mGET /image?id=37&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:06,603 INFO     127.0.0.1 - - [24/Jan/2024 20:13:06] "[37mGET /image?id=41&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:06,975 INFO     127.0.0.1 - - [24/Jan/2024 20:13:06] "[37mGET /image?id=40&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:07,266 INFO     127.0.0.1 - - [24/Jan/2024 20:13:07] "[37mGET /image?id=39&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:07,350 INFO     127.0.0.1 - - [24/Jan/2024 20:13:07] "[37mGET /image?id=23&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:07,583 INFO     127.0.0.1 - - [24/Jan/2024 20:13:07] "[37mGET /image?id=21&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:08,845 INFO     127.0.0.1 - - [24/Jan/2024 20:13:08] "[37mGET /image?id=20&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:09,193 INFO     127.0.0.1 - - [24/Jan/2024 20:13:09] "[37mGET /image?id=11&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:10,009 INFO     127.0.0.1 - - [24/Jan/2024 20:13:10] "[37mGET /image?id=22&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:10,166 INFO     127.0.0.1 - - [24/Jan/2024 20:13:10] "[37mGET /image?id=34&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:10,218 INFO     127.0.0.1 - - [24/Jan/2024 20:13:10] "[37mGET /image?id=24&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:10,223 INFO     127.0.0.1 - - [24/Jan/2024 20:13:10] "[37mGET /image?id=15&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:11,467 INFO     127.0.0.1 - - [24/Jan/2024 20:13:11] "[37mGET /image?id=25&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:13,380 INFO     127.0.0.1 - - [24/Jan/2024 20:13:13] "[37mGET /image?id=13&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:13,383 INFO     127.0.0.1 - - [24/Jan/2024 20:13:13] "[37mGET /image?id=36&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:13,586 INFO     127.0.0.1 - - [24/Jan/2024 20:13:13] "[37mGET /image?id=29&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:13,590 INFO     127.0.0.1 - - [24/Jan/2024 20:13:13] "[37mGET /image?id=38&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:14,130 INFO     127.0.0.1 - - [24/Jan/2024 20:13:14] "[37mGET /image?id=28&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:15,978 INFO     127.0.0.1 - - [24/Jan/2024 20:13:15] "[37mGET /image?id=17&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:16,246 INFO     127.0.0.1 - - [24/Jan/2024 20:13:16] "[37mGET /image?id=32&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:16,465 INFO     127.0.0.1 - - [24/Jan/2024 20:13:16] "[37mGET /image?id=8&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:16,893 INFO     127.0.0.1 - - [24/Jan/2024 20:13:16] "[37mGET /image?id=16&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:17,375 INFO     127.0.0.1 - - [24/Jan/2024 20:13:17] "[37mGET /image?id=7&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:18,840 INFO     127.0.0.1 - - [24/Jan/2024 20:13:18] "[37mGET /image?id=9&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:18,855 INFO     127.0.0.1 - - [24/Jan/2024 20:13:18] "[33mGET /image?id=43&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:13:19,033 INFO     127.0.0.1 - - [24/Jan/2024 20:13:19] "[37mGET /image?id=3&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:13:22,464 INFO     127.0.0.1 - - [24/Jan/2024 20:13:22] "[37mGET /image?id=30&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:41,344 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:14:47,587 INFO     127.0.0.1 - - [24/Jan/2024 20:14:47] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:14:50,698 INFO     127.0.0.1 - - [24/Jan/2024 20:14:50] "[37mGET /dataset/product.product HTTP/1.1[0m" 200 -
2024-01-24 20:14:56,413 INFO     127.0.0.1 - - [24/Jan/2024 20:14:56] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:59,310 INFO     127.0.0.1 - - [24/Jan/2024 20:14:59] "[37mGET /image?id=14&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:59,610 INFO     127.0.0.1 - - [24/Jan/2024 20:14:59] "[37mGET /image?id=27&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:59,745 INFO     127.0.0.1 - - [24/Jan/2024 20:14:59] "[37mGET /image?id=26&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:59,861 INFO     127.0.0.1 - - [24/Jan/2024 20:14:59] "[37mGET /image?id=33&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:59,983 INFO     127.0.0.1 - - [24/Jan/2024 20:14:59] "[37mGET /image?id=35&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:14:59,990 INFO     127.0.0.1 - - [24/Jan/2024 20:14:59] "[37mGET /image?id=10&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:02,029 INFO     127.0.0.1 - - [24/Jan/2024 20:15:02] "[37mGET /image?id=31&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:02,637 INFO     127.0.0.1 - - [24/Jan/2024 20:15:02] "[37mGET /image?id=42&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:02,742 INFO     127.0.0.1 - - [24/Jan/2024 20:15:02] "[37mGET /image?id=19&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:02,970 INFO     127.0.0.1 - - [24/Jan/2024 20:15:02] "[37mGET /image?id=39&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:03,095 INFO     127.0.0.1 - - [24/Jan/2024 20:15:03] "[37mGET /image?id=11&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:03,208 INFO     127.0.0.1 - - [24/Jan/2024 20:15:03] "[37mGET /image?id=34&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:04,830 INFO     127.0.0.1 - - [24/Jan/2024 20:15:04] "[37mGET /image?id=22&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:06,156 INFO     127.0.0.1 - - [24/Jan/2024 20:15:06] "[37mGET /image?id=23&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:06,614 INFO     127.0.0.1 - - [24/Jan/2024 20:15:06] "[37mGET /image?id=20&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:06,616 INFO     127.0.0.1 - - [24/Jan/2024 20:15:06] "[37mGET /image?id=1&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:06,818 INFO     127.0.0.1 - - [24/Jan/2024 20:15:06] "[37mGET /image?id=15&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:06,858 INFO     127.0.0.1 - - [24/Jan/2024 20:15:06] "[37mGET /image?id=41&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:08,904 INFO     127.0.0.1 - - [24/Jan/2024 20:15:08] "[37mGET /image?id=18&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:09,292 INFO     127.0.0.1 - - [24/Jan/2024 20:15:09] "[37mGET /dataset/product.product HTTP/1.1[0m" 200 -
2024-01-24 20:15:10,146 INFO     127.0.0.1 - - [24/Jan/2024 20:15:10] "[37mGET /image?id=25&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:10,286 INFO     127.0.0.1 - - [24/Jan/2024 20:15:10] "[37mGET /image?id=37&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:10,373 INFO     127.0.0.1 - - [24/Jan/2024 20:15:10] "[37mGET /image?id=40&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:10,595 INFO     127.0.0.1 - - [24/Jan/2024 20:15:10] "[37mGET /image?id=21&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:11,071 INFO     127.0.0.1 - - [24/Jan/2024 20:15:11] "[37mGET /image?id=12&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:12,440 INFO     127.0.0.1 - - [24/Jan/2024 20:15:12] "[37mGET /image?id=24&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:13,784 INFO     127.0.0.1 - - [24/Jan/2024 20:15:13] "[37mGET /image?id=36&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:13,976 INFO     127.0.0.1 - - [24/Jan/2024 20:15:13] "[37mGET /image?id=30&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:14,250 INFO     127.0.0.1 - - [24/Jan/2024 20:15:14] "[37mGET /image?id=38&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:14,706 INFO     127.0.0.1 - - [24/Jan/2024 20:15:14] "[37mGET /image?id=13&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:14,952 INFO     127.0.0.1 - - [24/Jan/2024 20:15:14] "[37mGET /image?id=29&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:16,206 INFO     127.0.0.1 - - [24/Jan/2024 20:15:16] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:16,682 INFO     127.0.0.1 - - [24/Jan/2024 20:15:16] "[37mGET /image?id=28&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:17,439 INFO     127.0.0.1 - - [24/Jan/2024 20:15:17] "[37mGET /image?id=17&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:17,541 INFO     127.0.0.1 - - [24/Jan/2024 20:15:17] "[37mGET /image?id=9&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:18,247 INFO     127.0.0.1 - - [24/Jan/2024 20:15:18] "[37mGET /image?id=32&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:18,256 INFO     127.0.0.1 - - [24/Jan/2024 20:15:18] "[37mGET /image?id=3&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:18,415 INFO     127.0.0.1 - - [24/Jan/2024 20:15:18] "[37mGET /image?id=16&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:18,976 INFO     127.0.0.1 - - [24/Jan/2024 20:15:18] "[37mGET /image?id=8&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:19,345 INFO     127.0.0.1 - - [24/Jan/2024 20:15:19] "[37mGET /image?id=7&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:15:19,401 INFO     127.0.0.1 - - [24/Jan/2024 20:15:19] "[33mGET /image?id=43&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:24:26,267 ERROR    Exception on /dataset/it.ui.report [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'it.ui.report'
2024-01-24 20:24:26,277 INFO     127.0.0.1 - - [24/Jan/2024 20:24:26] "[35m[1mGET /dataset/it.ui.report HTTP/1.1[0m" 500 -
2024-01-24 20:26:38,846 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:26:43,536 INFO     127.0.0.1 - - [24/Jan/2024 20:26:43] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:26:55,312 ERROR    Exception on /dataset/ir.actions.report [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'ir.actions.report'
2024-01-24 20:26:55,316 INFO     127.0.0.1 - - [24/Jan/2024 20:26:55] "[35m[1mGET /dataset/ir.actions.report HTTP/1.1[0m" 500 -
2024-01-24 20:27:38,294 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:27:42,839 INFO     127.0.0.1 - - [24/Jan/2024 20:27:42] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:28:10,018 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:28:14,097 INFO     127.0.0.1 - - [24/Jan/2024 20:28:14] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:28:18,173 INFO     127.0.0.1 - - [24/Jan/2024 20:28:18] "[37mGET /dataset/product.product HTTP/1.1[0m" 200 -
2024-01-24 20:28:22,007 INFO     127.0.0.1 - - [24/Jan/2024 20:28:22] "[37mGET /dataset/product.template HTTP/1.1[0m" 200 -
2024-01-24 20:28:23,281 INFO     127.0.0.1 - - [24/Jan/2024 20:28:23] "[37mGET /dataset/product.template HTTP/1.1[0m" 200 -
2024-01-24 20:29:01,725 INFO     127.0.0.1 - - [24/Jan/2024 20:29:01] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:04,716 INFO     127.0.0.1 - - [24/Jan/2024 20:29:04] "[37mGET /image?id=14&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:04,818 INFO     127.0.0.1 - - [24/Jan/2024 20:29:04] "[37mGET /image?id=33&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:04,994 INFO     127.0.0.1 - - [24/Jan/2024 20:29:04] "[37mGET /image?id=35&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:05,030 INFO     127.0.0.1 - - [24/Jan/2024 20:29:05] "[37mGET /image?id=27&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:05,185 INFO     127.0.0.1 - - [24/Jan/2024 20:29:05] "[37mGET /image?id=26&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:05,191 INFO     127.0.0.1 - - [24/Jan/2024 20:29:05] "[37mGET /image?id=10&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:07,911 ERROR    Exception on /dataset/ir.actions.report [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'ir.actions.report'
2024-01-24 20:29:07,920 INFO     127.0.0.1 - - [24/Jan/2024 20:29:07] "[35m[1mGET /dataset/ir.actions.report HTTP/1.1[0m" 500 -
2024-01-24 20:29:07,934 INFO     127.0.0.1 - - [24/Jan/2024 20:29:07] "[37mGET /image?id=19&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:08,237 INFO     127.0.0.1 - - [24/Jan/2024 20:29:08] "[37mGET /image?id=31&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:08,534 INFO     127.0.0.1 - - [24/Jan/2024 20:29:08] "[37mGET /image?id=22&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:08,644 INFO     127.0.0.1 - - [24/Jan/2024 20:29:08] "[37mGET /image?id=11&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:08,883 INFO     127.0.0.1 - - [24/Jan/2024 20:29:08] "[37mGET /image?id=18&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:09,022 INFO     127.0.0.1 - - [24/Jan/2024 20:29:09] "[37mGET /image?id=15&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:10,962 INFO     127.0.0.1 - - [24/Jan/2024 20:29:10] "[37mGET /image?id=20&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:11,803 INFO     127.0.0.1 - - [24/Jan/2024 20:29:11] "[37mGET /image?id=23&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:12,046 INFO     127.0.0.1 - - [24/Jan/2024 20:29:12] "[37mGET /image?id=1&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:12,139 INFO     127.0.0.1 - - [24/Jan/2024 20:29:12] "[37mGET /image?id=34&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:12,693 INFO     127.0.0.1 - - [24/Jan/2024 20:29:12] "[37mGET /image?id=41&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:13,001 INFO     127.0.0.1 - - [24/Jan/2024 20:29:13] "[37mGET /image?id=42&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:14,200 INFO     127.0.0.1 - - [24/Jan/2024 20:29:14] "[37mGET /image?id=39&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:15,290 INFO     127.0.0.1 - - [24/Jan/2024 20:29:15] "[37mGET /image?id=25&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:15,884 INFO     127.0.0.1 - - [24/Jan/2024 20:29:15] "[37mGET /image?id=21&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:16,009 INFO     127.0.0.1 - - [24/Jan/2024 20:29:16] "[37mGET /image?id=40&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:16,082 INFO     127.0.0.1 - - [24/Jan/2024 20:29:16] "[37mGET /image?id=12&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:17,388 INFO     127.0.0.1 - - [24/Jan/2024 20:29:17] "[37mGET /image?id=37&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:18,835 INFO     127.0.0.1 - - [24/Jan/2024 20:29:18] "[37mGET /image?id=24&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:19,920 INFO     127.0.0.1 - - [24/Jan/2024 20:29:19] "[37mGET /image?id=36&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:20,434 INFO     127.0.0.1 - - [24/Jan/2024 20:29:20] "[37mGET /image?id=13&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:20,526 INFO     127.0.0.1 - - [24/Jan/2024 20:29:20] "[37mGET /image?id=38&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:21,400 INFO     127.0.0.1 - - [24/Jan/2024 20:29:21] "[37mGET /image?id=30&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:22,642 INFO     127.0.0.1 - - [24/Jan/2024 20:29:22] "[37mGET /image?id=29&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:23,883 INFO     127.0.0.1 - - [24/Jan/2024 20:29:23] "[37mGET /image?id=28&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:25,419 INFO     127.0.0.1 - - [24/Jan/2024 20:29:25] "[37mGET /image?id=9&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:25,436 INFO     127.0.0.1 - - [24/Jan/2024 20:29:25] "[37mGET /image?id=17&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:25,648 INFO     127.0.0.1 - - [24/Jan/2024 20:29:25] "[37mGET /image?id=32&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:25,681 INFO     127.0.0.1 - - [24/Jan/2024 20:29:25] "[37mGET /image?id=16&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:26,132 INFO     127.0.0.1 - - [24/Jan/2024 20:29:26] "[37mGET /image?id=3&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:26,537 INFO     127.0.0.1 - - [24/Jan/2024 20:29:26] "[37mGET /image?id=8&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:29:27,180 INFO     127.0.0.1 - - [24/Jan/2024 20:29:27] "[33mGET /image?id=43&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:29:27,190 INFO     127.0.0.1 - - [24/Jan/2024 20:29:27] "[37mGET /image?id=7&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:01,281 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:32:18,931 INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-01-24 20:32:24,125 INFO     127.0.0.1 - - [24/Jan/2024 20:32:24] "[37mGET / HTTP/1.1[0m" 200 -
2024-01-24 20:32:27,916 INFO     127.0.0.1 - - [24/Jan/2024 20:32:27] "[37mGET /dataset/res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:30,966 INFO     127.0.0.1 - - [24/Jan/2024 20:32:30] "[37mGET /image?id=26&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:31,030 INFO     127.0.0.1 - - [24/Jan/2024 20:32:31] "[37mGET /image?id=27&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:31,302 INFO     127.0.0.1 - - [24/Jan/2024 20:32:31] "[37mGET /image?id=35&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:31,336 INFO     127.0.0.1 - - [24/Jan/2024 20:32:31] "[37mGET /image?id=14&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:31,401 INFO     127.0.0.1 - - [24/Jan/2024 20:32:31] "[37mGET /image?id=33&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:31,555 INFO     127.0.0.1 - - [24/Jan/2024 20:32:31] "[37mGET /image?id=10&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:32,631 ERROR    Exception on /dataset/ir.actions.report [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'ir.actions.report'
2024-01-24 20:32:32,650 INFO     127.0.0.1 - - [24/Jan/2024 20:32:32] "[35m[1mGET /dataset/ir.actions.report HTTP/1.1[0m" 500 -
2024-01-24 20:32:34,225 INFO     127.0.0.1 - - [24/Jan/2024 20:32:34] "[37mGET /image?id=41&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:34,568 INFO     127.0.0.1 - - [24/Jan/2024 20:32:34] "[37mGET /image?id=25&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:34,934 INFO     127.0.0.1 - - [24/Jan/2024 20:32:34] "[37mGET /image?id=34&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:35,146 INFO     127.0.0.1 - - [24/Jan/2024 20:32:35] "[37mGET /image?id=15&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:35,235 INFO     127.0.0.1 - - [24/Jan/2024 20:32:35] "[37mGET /image?id=37&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:35,447 INFO     127.0.0.1 - - [24/Jan/2024 20:32:35] "[37mGET /image?id=31&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:37,410 INFO     127.0.0.1 - - [24/Jan/2024 20:32:37] "[37mGET /image?id=18&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:38,068 ERROR    Exception on /dataset/ir.actions.act_window [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'ir.actions.act_window'
2024-01-24 20:32:38,069 INFO     127.0.0.1 - - [24/Jan/2024 20:32:38] "[35m[1mGET /dataset/ir.actions.act_window HTTP/1.1[0m" 500 -
2024-01-24 20:32:38,353 INFO     127.0.0.1 - - [24/Jan/2024 20:32:38] "[37mGET /image?id=42&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:38,420 INFO     127.0.0.1 - - [24/Jan/2024 20:32:38] "[37mGET /image?id=21&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:38,659 INFO     127.0.0.1 - - [24/Jan/2024 20:32:38] "[37mGET /image?id=40&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:39,430 INFO     127.0.0.1 - - [24/Jan/2024 20:32:39] "[37mGET /image?id=24&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:39,478 ERROR    Exception on /dataset/ir.actions.report [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'ir.actions.report'
2024-01-24 20:32:39,480 INFO     127.0.0.1 - - [24/Jan/2024 20:32:39] "[35m[1mGET /dataset/ir.actions.report HTTP/1.1[0m" 500 -
2024-01-24 20:32:39,785 INFO     127.0.0.1 - - [24/Jan/2024 20:32:39] "[37mGET /image?id=23&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:41,462 INFO     127.0.0.1 - - [24/Jan/2024 20:32:41] "[37mGET /image?id=20&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:42,044 INFO     127.0.0.1 - - [24/Jan/2024 20:32:42] "[37mGET /image?id=11&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:42,330 INFO     127.0.0.1 - - [24/Jan/2024 20:32:42] "[37mGET /image?id=22&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:42,459 INFO     127.0.0.1 - - [24/Jan/2024 20:32:42] "[37mGET /image?id=12&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:42,759 INFO     127.0.0.1 - - [24/Jan/2024 20:32:42] "[37mGET /image?id=1&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:43,010 INFO     127.0.0.1 - - [24/Jan/2024 20:32:43] "[37mGET /image?id=39&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:44,457 INFO     127.0.0.1 - - [24/Jan/2024 20:32:44] "[37mGET /image?id=19&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:46,033 INFO     127.0.0.1 - - [24/Jan/2024 20:32:46] "[37mGET /image?id=36&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:46,216 INFO     127.0.0.1 - - [24/Jan/2024 20:32:46] "[37mGET /image?id=30&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:46,648 INFO     127.0.0.1 - - [24/Jan/2024 20:32:46] "[37mGET /image?id=38&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:46,682 INFO     127.0.0.1 - - [24/Jan/2024 20:32:46] "[37mGET /image?id=29&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:46,934 INFO     127.0.0.1 - - [24/Jan/2024 20:32:46] "[37mGET /image?id=13&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:48,173 INFO     127.0.0.1 - - [24/Jan/2024 20:32:48] "[37mGET /image?id=28&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:49,151 INFO     127.0.0.1 - - [24/Jan/2024 20:32:49] "[37mGET /image?id=9&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:49,823 INFO     127.0.0.1 - - [24/Jan/2024 20:32:49] "[37mGET /image?id=17&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:50,972 INFO     127.0.0.1 - - [24/Jan/2024 20:32:50] "[37mGET /image?id=32&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:51,092 INFO     127.0.0.1 - - [24/Jan/2024 20:32:51] "[37mGET /image?id=3&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:51,204 INFO     127.0.0.1 - - [24/Jan/2024 20:32:51] "[37mGET /image?id=16&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:51,767 INFO     127.0.0.1 - - [24/Jan/2024 20:32:51] "[37mGET /image?id=8&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:52,106 INFO     127.0.0.1 - - [24/Jan/2024 20:32:52] "[37mGET /image?id=7&model=res.partner HTTP/1.1[0m" 200 -
2024-01-24 20:32:52,243 INFO     127.0.0.1 - - [24/Jan/2024 20:32:52] "[33mGET /image?id=43&model=res.partner HTTP/1.1[0m" 404 -
2024-01-24 20:33:12,619 ERROR    Exception on /dataset/ir.action.report [GET]
Traceback (most recent call last):
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/felino/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/felino/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/felino/Documents/docker/server/app.py", line 180, in partner
    partners   = odoo[data[models]['model'] ].search_read([],data[models]['field'].split(','))
KeyError: 'ir.action.report'
2024-01-24 20:33:12,621 INFO     127.0.0.1 - - [24/Jan/2024 20:33:12] "[35m[1mGET /dataset/ir.action.report HTTP/1.1[0m" 500 -
